### ISSUE TITLE
pre-release 0.2

### ISSUE THREAD

**Issue by aress31** [ephracis/hermes#2]
Hi ephracis,

It seems that you forgot to upload your new src code in the pre-release 0.2. Also, if the problem comes from the captcha as you told me (because I printed what was returned by the google server and on the html content I haven't saw any captcha code to enter), I found python modules to solve captcha pictures.
So if the evasion technique does not work we can still try to use one of this python module.

Cheers

**Comment by ephracis** [comment]
It should be there. Have you checked https://github.com/ephracis/hermes/releases/tag/0.2?

Maybe there are more then one error occurring? I also printed out the HTML and I saw something along the lines with "we are detecting an unusual amount of traffic from you". I was in a hurry so I didn't check the whole content, maybe they have something other than a normal captcha, maybe a login form.

But in any case, if this wait-and-login thing doesn't work, and you find another way to get around Googles defence, I would very much appreciate it. Unfortunately I don't have much spare time at the moment.

**Comment by aress31** [comment]
Actually I noticed something weird, I don't know what cause that but the
hermes program seems to run normally when I used it in someone office I
could get the whole list of applications to fetch and then the downloading
was starting but as it takes some times I interrupted it and at home with
my internet connection it doesn't work so it may be related to the bandwth
or something like that because I have noticed that each response comes with
its ttl so maybe the connection can impact on it but I am not sure.

2015-03-25 16:09 GMT+01:00 Christoffer Brodd-Reijer <
notifications@github.com>:

**Comment by ephracis** [comment]
No idea. It is the Python library GooglePlayAPI that does the listing and downloading. So I don't know really what goes on behind the scenes. They have command line tools where you can manually list and download apk files.
